import Head from "next/head";
// import { BsFillMoonStarsFill } from "react-icons/bs";
import Navbar from "../components/Navbar";
// import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
// import Image from "next/image";
// import eli from "../public/profile-image.jpeg";
import AboutMe from "../components/AboutMe";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eliezer Encarnacion Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        
        <section className="min-h-screen">

          <Navbar />
          {/* <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons">EliezerCoding</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className=" cursor-pointer text-2xl" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav> */}

          <AboutMe />
          {/* <div className="text-center p-10">
            <h2 className="text-5xl py-5 text-teal-600 font-medium">Eliezer Encarnacion</h2>
            <h3 className="text-2xl py-2">Web and Software Developer</h3>
            <p className="text-base py-5 leading-8 text-gray-800">
              A Front-End Web Developer passionate about creating interactive applications and experiences on the web!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-20 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={eli} fill />
          </div> */}

        </section>
        
      </main>
    </div>
  )
}
