import Head from "next/head";
// import { BsFillMoonStarsFill } from "react-icons/bs";
import Navbar from "../components/Navbar";
// import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
// import Image from "next/image";
// import eli from "../public/profile-image.jpeg";
import AboutMe from "../components/AboutMe";
import Profile from "../components/Profile";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eliezer Encarnacion Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png"/>
      </Head>

      <Navbar />
      <main className="bg-slate-100 px-10">
        
        {/* <section className="min-h-screen">

          <Navbar />
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-burtons">EliezerCoding</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className=" cursor-pointer text-2xl" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>

          <AboutMe />
          <div className="text-center p-10">
            <h2 className="text-5xl py-5 text-teal-600 font-medium">Eliezer Encarnacion</h2>
            <h3 className="text-2xl py-2">Web and Software Developer</h3>
            <p className="text-base py-5 leading-8 text-gray-800">
              A Front-End Web Developer passionate about creating interactive applications and experiences on the web!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-20 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={eli} fill />
          </div>

        </section>

        <section>

          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-base py-2 leading-8 text-gray-800">I'm a web developer with a focus on the <span className="text-teal-500">MERN</span> stack, but still exploring other <span className="text-teal-500">technologies</span> and <span className="text-teal-500">frameworks</span> that catch my interest! If your are looking for a developer to add to your <span className="text-teal-500">team</span>, I'd love to hear from you!</p>
          </div>

        </section>

        <section>
          <ul>
            <li>- HTML</li>
            <li>- CSS</li>
            <li>- JavaScript</li>
            <li>- React</li>
            <li>- Java</li>
            <li>- Spring Boot</li>
            <li>- REST API</li>
            <li>- MySQL</li>
            <li>- MongoDB</li>
            <li>- Git</li>
            <li>- VS Code</li>
            <li>- IntelliJ IDEA</li>
          </ul>
        </section> */}

        

        <Profile />

        {/* <AboutMe /> */}

        <About />
        <Skills />
        <Projects />
        <Contact />
        
      </main>

      <Footer />
    </div>
  )
}
